### ISSUE TITLE
Step 4 Problem

### ISSUE THREAD

**Issue by JoeLajoe** [basdp/USB-Turntables-to-Sonos-with-RPi#1]
Ran into a problem running the code 
arecord -D dmic_sv -r 44100 -f S16_LE -c 2 --vumeter=stereo /dev/null

got the error
arecord: main:828: audio open error: No such file or directory

any suggestion would be greatly appreciated.

**Comment by basdp** [comment]
Maybe these tips can help?
https://github.com/synesthesiam/voice2json/issues/28

If not, can you post the output of `arecord -L` here?
