### ISSUE TITLE
Step 6 - password

### ISSUE THREAD

**Issue by alonggoneconfusion** [basdp/USB-Turntables-to-Sonos-with-RPi#3]
While setting this up on a raspbery pi I found that the additional spaces in the /etc/darkice.cfg for the passowrd line:
password        = raspberry    # source password for the IceCast2 server

caused it to fail to connect to the isecast2 server. I used the following instead and it connected as required:
password=raspberry

**Comment by basdp** [comment]
Thanks, I'll update it in the repo!
